### ISSUE TITLE
Why do we need to requeue when we fail process the message in Google Worker?

### ISSUE THREAD

**Issue by atthoriq** [febytanzil/gobroker#27]
Hi, first of all, I don't consider it an issue, yet. But I don't know where to put my question regarding this codebase.

I am a newbie using publisher and subscriber both on RabbitMQ and Google Pubsub. I found your code that wraps google pubsub default client. It is very easy to use, thank you, but when I look into the detail of the code, I am intrigued by the way this client handle error when processing messages by republishing into the same topic. My question is why? why do we need to republishing the message? Instead, google pubsub default client by default would handle redelivery when we don't acknowledge it or calling `Nack()`. 

I aim to not having a duplicate message. So the number of my unacknowledge message would stay low. Thank you in advance for your explanation.

---
edit 1: The message wouldn't be duplicated because it will be acked eventually. But I don't think republishing is a good idea.

**Comment by febytanzil** [comment]
@atthoriq 

Hi, it's actually for limiting the requeue occurrence, afaik google pubsub lib doesn't provide a feature yet to limit how many times the message will be requeued if you use their `Nack()` (infinite requeue until ack), and as an engineer sometimes you would like to limit how many times do you want to process a message that being requeued multiple times already and just give up, discard the message or try to republish the message another time (most of the cases that I've found are corrupted/ invalid message & 3rd party APIs that are down such as SMTP server, payment gateway etc.) and the other reason for these kind of messages don't block the subscriber to process other message in the queue server memory as well. And this one I believe is giving better leverage to the engineers than avoiding delivering message more than once to all subscribers/ consumers.

https://cloud.google.com/pubsub/docs/subscriber#at-least-once-delivery
and in any case, it could deliver the same message more than once, it's the responsibility of the consumers to handle the duplicates
> Typically, Pub/Sub delivers each message once and in the order in which it was published. However, messages may sometimes be delivered out of order or more than once. In general, accommodating more-than-once delivery requires your subscriber to be idempotent when processing messages.

**Comment by atthoriq** [comment]
@febytanzil Oh, I see. I understand your concern. For my use-case, there are only 2 possibilities either it is being republished infinitely (caused by invalid message) or put it into other topic behaves like dead letter topic. So there's no chance for my consumer to losing it after several numbers of republishing. 

Anyway, thank you!

**Comment by febytanzil** [comment]
@atthoriq 

one way I can suggest, you could use `Attempts` from the Message struct
`
type Message struct {
	Body        []byte
	Attempts    int
	ContentType string
}
`
that can tell you how many attempts of requeue already occurred for that particular message, so by the time it hits the limit that you specify, you can publish it to the dead letter topic etc.

hope this helps!
